# Generated by Django 3.2.4 on 2021-06-03 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210603_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='local',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Local do Evento'),
        ),
    ]
